// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `books` table.
    ///
    /// (Automatically generated by Diesel.)
    books (id) {
        /// The `id` column of the `books` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `title` column of the `books` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        title -> Varchar,
        /// The `author` column of the `books` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        author -> Varchar,
        /// The `description` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `status` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Nullable<Int4>,
        /// The `rating` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        rating -> Nullable<Float8>,
        /// The `added_date` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Date>`.
        ///
        /// (Automatically generated by Diesel.)
        added_date -> Nullable<Date>,
        /// The `cover_url` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        cover_url -> Nullable<Varchar>,
        /// The `extension` column of the `books` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        extension -> Nullable<Varchar>,
    }
}
